[build]
  base = "frontend"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/contacto"
  to = "/.netlify/functions/contacto"
  status = 200

[[redirects]]
  from = "/api/welcome"
  to = "/.netlify/functions/welcome"
  status = 200