// Tipos obtenidos del OpenAPI de Supabase; restricciones de extra_sessions
// documentadas en PLAN_FASES.md. No se conecta a servicios externos.
export const esquemaBase = `
create role anon; create role authenticated; create role service_role bypassrls;
create table users(id uuid primary key, role text, created_at timestamptz default now());
create table sessions(id bigint generated by default as identity primary key, type text, price float8, title text);
create table suscriptions(sub_id uuid primary key default gen_random_uuid(), user_id uuid references users(id),
  plan text, status text, mp_sub_id text, init_date timestamp, end_date timestamp, price real, failed_at timestamp);
create table pagos(id bigint generated by default as identity primary key, mp_payment_id text not null unique,
  user_id uuid references users(id), sesion_id bigint, monto numeric, moneda text default 'MXN', estado_mp text,
  tipo text, metadata jsonb, created_at timestamptz default now());
create table extra_sessions(id bigint generated by default as identity primary key, user_id uuid references users(id),
  session_id bigint references sessions(id), price float8, pur_date timestamp, mp_pay_id text,
  status text not null default 'pending' check(status in ('pending','pagada','rechazada')));
create unique index uniq_extra_sessions_user_sesion_activa on extra_sessions(user_id,session_id) where status <> 'rechazada';
create unique index uniq_extra_sessions_mp_pay_id on extra_sessions(mp_pay_id) where mp_pay_id is not null;
grant usage on schema public to service_role, anon, authenticated;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
`;
